const photoActionTypes = {
    UPLOAD_PHOTO: 'UPLOAD_PHOTO',
    SHOW_PHOTOS: 'SHOW_PHOTOS',
    SHOW_PHOTO_DETAIL: 'SHOW_PHOTO_DETAIL',
    SEARCH_PHOTO: 'SEARCH_PHOTO',
    UPDATE_PHOTO_TITLE: 'UPDATE_PHOTO_TITLE',
    UPDATE_IMAGE: 'UPDATE_IMAGE',
    DELETE_PHOTO: 'DELETE_PHOTO',
    PHOTO_ERROR: 'PHOTO_ERROR',
};

export default photoActionTypes;
